bazel build --config=mingw_config --cxxopt=-D_KR_PLATFORM_WINDOWS_ --explain=log.txt --verbose_explanations //...
bazel run --config=mingw_config --cxxopt=-D_KR_PLATFORM_WINDOWS_ //Clients/Sandbox/src:Sandbox
PAUSE